"""transaction table

Revision ID: 849703b5eb72
Revises: 88baed878460
Create Date: 2018-11-10 13:58:34.645079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849703b5eb72'
down_revision = '88baed878460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('txn_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
