"""users table with updated nullability

Revision ID: 88baed878460
Revises: 1fbf0955af25
Create Date: 2018-11-09 13:42:36.793618

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88baed878460'
down_revision = '1fbf0955af25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'balance',
                    existing_type=mysql.DECIMAL(6, 2),
                    nullable=True)
    op.alter_column('user', 'created_date',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.alter_column('user', 'updated_date',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_date',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.alter_column('user', 'created_date',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.alter_column('user', 'balance',
                    existing_type=mysql.DECIMAL(precision=2, scale=0),
                    nullable=True)
    # ### end Alembic commands ###
